// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: technician/technician.proto

package technician

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request and Response messages
type CreateTechnicianRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopId   string  `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	HourRate float64 `protobuf:"fixed64,3,opt,name=hour_rate,json=hourRate,proto3" json:"hour_rate,omitempty"`
}

func (x *CreateTechnicianRequest) Reset() {
	*x = CreateTechnicianRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_technician_technician_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTechnicianRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTechnicianRequest) ProtoMessage() {}

func (x *CreateTechnicianRequest) ProtoReflect() protoreflect.Message {
	mi := &file_technician_technician_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTechnicianRequest.ProtoReflect.Descriptor instead.
func (*CreateTechnicianRequest) Descriptor() ([]byte, []int) {
	return file_technician_technician_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTechnicianRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *CreateTechnicianRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTechnicianRequest) GetHourRate() float64 {
	if x != nil {
		return x.HourRate
	}
	return 0
}

type CreateTechnicianResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TechnicianId string `protobuf:"bytes,1,opt,name=technician_id,json=technicianId,proto3" json:"technician_id,omitempty"`
}

func (x *CreateTechnicianResponse) Reset() {
	*x = CreateTechnicianResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_technician_technician_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTechnicianResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTechnicianResponse) ProtoMessage() {}

func (x *CreateTechnicianResponse) ProtoReflect() protoreflect.Message {
	mi := &file_technician_technician_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTechnicianResponse.ProtoReflect.Descriptor instead.
func (*CreateTechnicianResponse) Descriptor() ([]byte, []int) {
	return file_technician_technician_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTechnicianResponse) GetTechnicianId() string {
	if x != nil {
		return x.TechnicianId
	}
	return ""
}

type GetTechnicianRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TechnicianId string `protobuf:"bytes,1,opt,name=technician_id,json=technicianId,proto3" json:"technician_id,omitempty"`
}

func (x *GetTechnicianRequest) Reset() {
	*x = GetTechnicianRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_technician_technician_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTechnicianRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTechnicianRequest) ProtoMessage() {}

func (x *GetTechnicianRequest) ProtoReflect() protoreflect.Message {
	mi := &file_technician_technician_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTechnicianRequest.ProtoReflect.Descriptor instead.
func (*GetTechnicianRequest) Descriptor() ([]byte, []int) {
	return file_technician_technician_proto_rawDescGZIP(), []int{2}
}

func (x *GetTechnicianRequest) GetTechnicianId() string {
	if x != nil {
		return x.TechnicianId
	}
	return ""
}

type ListTechniciansRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopId string `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
}

func (x *ListTechniciansRequest) Reset() {
	*x = ListTechniciansRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_technician_technician_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTechniciansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTechniciansRequest) ProtoMessage() {}

func (x *ListTechniciansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_technician_technician_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTechniciansRequest.ProtoReflect.Descriptor instead.
func (*ListTechniciansRequest) Descriptor() ([]byte, []int) {
	return file_technician_technician_proto_rawDescGZIP(), []int{3}
}

func (x *ListTechniciansRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

type ListTechniciansResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Technicians []*Technician `protobuf:"bytes,1,rep,name=technicians,proto3" json:"technicians,omitempty"`
}

func (x *ListTechniciansResponse) Reset() {
	*x = ListTechniciansResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_technician_technician_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTechniciansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTechniciansResponse) ProtoMessage() {}

func (x *ListTechniciansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_technician_technician_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTechniciansResponse.ProtoReflect.Descriptor instead.
func (*ListTechniciansResponse) Descriptor() ([]byte, []int) {
	return file_technician_technician_proto_rawDescGZIP(), []int{4}
}

func (x *ListTechniciansResponse) GetTechnicians() []*Technician {
	if x != nil {
		return x.Technicians
	}
	return nil
}

type Technician struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId   string  `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Name     string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	HourRate float64 `protobuf:"fixed64,4,opt,name=hour_rate,json=hourRate,proto3" json:"hour_rate,omitempty"` // Other fields as needed
}

func (x *Technician) Reset() {
	*x = Technician{}
	if protoimpl.UnsafeEnabled {
		mi := &file_technician_technician_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Technician) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Technician) ProtoMessage() {}

func (x *Technician) ProtoReflect() protoreflect.Message {
	mi := &file_technician_technician_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Technician.ProtoReflect.Descriptor instead.
func (*Technician) Descriptor() ([]byte, []int) {
	return file_technician_technician_proto_rawDescGZIP(), []int{5}
}

func (x *Technician) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Technician) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *Technician) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Technician) GetHourRate() float64 {
	if x != nil {
		return x.HourRate
	}
	return 0
}

var File_technician_technician_proto protoreflect.FileDescriptor

var file_technician_technician_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x2f, 0x74, 0x65, 0x63,
	0x68, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a,
	0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x69, 0x61,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f, 0x75, 0x72, 0x5f, 0x72, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x68, 0x6f, 0x75, 0x72, 0x52, 0x61,
	0x74, 0x65, 0x22, 0x3f, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x63, 0x68,
	0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x69, 0x61,
	0x6e, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69,
	0x63, 0x69, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x74,
	0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x49, 0x64,
	0x22, 0x31, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x69,
	0x61, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68,
	0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x68, 0x6f,
	0x70, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x63, 0x68, 0x6e,
	0x69, 0x63, 0x69, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d,
	0x0a, 0x0b, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e,
	0x52, 0x0b, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x73, 0x22, 0x66, 0x0a,
	0x0a, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73,
	0x68, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x68,
	0x6f, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f, 0x75, 0x72,
	0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x68, 0x6f, 0x75,
	0x72, 0x52, 0x61, 0x74, 0x65, 0x32, 0xd7, 0x01, 0x0a, 0x11, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69,
	0x63, 0x69, 0x61, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x10, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x12,
	0x18, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x69,
	0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x65, 0x63, 0x68, 0x6e,
	0x69, 0x63, 0x69, 0x61, 0x6e, 0x12, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x63, 0x68, 0x6e,
	0x69, 0x63, 0x69, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x54,
	0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x12, 0x44, 0x0a, 0x0f, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x73, 0x12, 0x17, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x63, 0x68,
	0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x61,
	0x62, 0x69, 0x61, 0x6e, 0x72, 0x77, 0x78, 0x2f, 0x6d, 0x79, 0x73, 0x68, 0x6f, 0x70, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_technician_technician_proto_rawDescOnce sync.Once
	file_technician_technician_proto_rawDescData = file_technician_technician_proto_rawDesc
)

func file_technician_technician_proto_rawDescGZIP() []byte {
	file_technician_technician_proto_rawDescOnce.Do(func() {
		file_technician_technician_proto_rawDescData = protoimpl.X.CompressGZIP(file_technician_technician_proto_rawDescData)
	})
	return file_technician_technician_proto_rawDescData
}

var file_technician_technician_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_technician_technician_proto_goTypes = []interface{}{
	(*CreateTechnicianRequest)(nil),  // 0: CreateTechnicianRequest
	(*CreateTechnicianResponse)(nil), // 1: CreateTechnicianResponse
	(*GetTechnicianRequest)(nil),     // 2: GetTechnicianRequest
	(*ListTechniciansRequest)(nil),   // 3: ListTechniciansRequest
	(*ListTechniciansResponse)(nil),  // 4: ListTechniciansResponse
	(*Technician)(nil),               // 5: Technician
}
var file_technician_technician_proto_depIdxs = []int32{
	5, // 0: ListTechniciansResponse.technicians:type_name -> Technician
	0, // 1: TechnicianService.CreateTechnician:input_type -> CreateTechnicianRequest
	2, // 2: TechnicianService.GetTechnician:input_type -> GetTechnicianRequest
	3, // 3: TechnicianService.ListTechnicians:input_type -> ListTechniciansRequest
	1, // 4: TechnicianService.CreateTechnician:output_type -> CreateTechnicianResponse
	5, // 5: TechnicianService.GetTechnician:output_type -> Technician
	4, // 6: TechnicianService.ListTechnicians:output_type -> ListTechniciansResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_technician_technician_proto_init() }
func file_technician_technician_proto_init() {
	if File_technician_technician_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_technician_technician_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTechnicianRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_technician_technician_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTechnicianResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_technician_technician_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTechnicianRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_technician_technician_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTechniciansRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_technician_technician_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTechniciansResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_technician_technician_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Technician); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_technician_technician_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_technician_technician_proto_goTypes,
		DependencyIndexes: file_technician_technician_proto_depIdxs,
		MessageInfos:      file_technician_technician_proto_msgTypes,
	}.Build()
	File_technician_technician_proto = out.File
	file_technician_technician_proto_rawDesc = nil
	file_technician_technician_proto_goTypes = nil
	file_technician_technician_proto_depIdxs = nil
}
