name: "Protocol Buffer Go Stubs Generator"
on:
  push:
    tags:
      - "**/v*.*.*" # Push events to matching v*, i.e. root/service_name/v1.0.0
jobs:
  protoc:
    name: "Generate"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["order"]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - uses: actions/checkout@v2
      - name: Extract Release Version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          SERVICE_NAME=$(echo $TAG_NAME | cut -d'/' -f2)
          VERSION=$(echo $TAG_NAME | cut -d'/' -f3)
          echo "SERVICE_NAME=${SERVICE_NAME}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${VERSION}" >> $GITHUB_ENV
      - name: "Generate for Golang"
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/run.sh"
          ./run.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }}
